import { getFibonacci } from "../utility/calc";

export const TITLE: string = "Even Fibonacci numbers";
export const NUMBER: number = 2;
export const USE_DATA: boolean = true;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...  
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

export function solve(): string {
    let solution: number = 0;
    let fibNum: number = 0;
    let index: number = 0;
    while (fibNum <= 4000000) {
      fibNum = getFibonacci(index);
      if (fibNum % 2 === 0) {
        solution += fibNum;
      }
      index++;
    }
    return solution.toString();
}